version: '3.2'
services: 
  postgres:
    # image: postgres
    build: './database'
    restart: 'always'
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gwp
    volumes: 
      - ./database/data:/var/lib/postgresql/data